name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: npm install
      working-directory: ./TestApp

    - name: Build App
      run: npm run build
      working-directory: ./TestApp
