name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      working-directory: ./TestApp
      run: npm install

    - name: Build App
      working-directory: ./TestApp
      run: npm run build
